# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            박25
tagline:          'A Jekyll theme'
url:              https://pakseon25.github.io

author:
  name:           'pakseon'
  url:            https://pakseon25.github.io

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            1.0.0
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/pakseon25

disqus.shortname: pakseon25
